In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

In [ ]:
pd.set_option('display.max_columns', None)
df = pd.read_csv('/content/SUPERSTORE.csv', encoding="latin-1" )

In [ ]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [ ]:
table_books = df[
    df['Sub-Category'].isin(['Bookcases','Tables'])
]

In [ ]:
table_books.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
10,11,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032,West,FUR-TA-10001539,Furniture,Tables,Chromcraft Rectangular Conference Tables,1706.1840,9,0.20,85.3092
24,25,CA-2015-106320,9/25/2015,9/30/2015,Standard Class,EB-13870,Emily Burns,Consumer,United States,Orem,Utah,84057,West,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,1044.6300,3,0.00,240.2649
27,28,US-2015-150630,9/17/2015,9/21/2015,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,Pennsylvania,19140,East,FUR-BO-10004834,Furniture,Bookcases,"Riverside Palais Royal Lawyers Bookcase, Royal...",3083.4300,7,0.50,-1665.0522

In [ ]:
total_revenue = table_books.groupby('Sub-Category')['Sales'].sum().reset_index()
total_revenue

  Sub-Category        Sales
0    Bookcases  114879.9963
1       Tables  206965.5320

In [ ]:
px.bar(
    total_revenue,
    x = 'Sub-Category',
    y = 'Sales'
)

In [ ]:
discount_sum = table_books.groupby(['Sub-Category','Discount'])['Sales'].sum().reset_index()
discount_sum

   Sub-Category  Discount       Sales
0     Bookcases      0.00  31935.9800
1     Bookcases      0.15  27558.5215
2     Bookcases      0.20  26841.4960
3     Bookcases      0.30   4282.6980
4     Bookcases      0.32  14493.4588
5     Bookcases      0.50   7308.4600
6     Bookcases      0.70   2459.3820
7        Tables      0.00  71578.7600
8        Tables      0.20  45430.2320
9        Tables      0.30  25182.1500
10       Tables      0.40  45614.4060
11       Tables      0.45   5484.9740
12       Tables      0.50  13675.0100

In [ ]:
px.line(
    discount_sum,
    x = 'Discount',
    y = 'Sales',
    color = 'Sub-Category'
)

In [ ]:
table_books.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
10,11,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032,West,FUR-TA-10001539,Furniture,Tables,Chromcraft Rectangular Conference Tables,1706.1840,9,0.20,85.3092
24,25,CA-2015-106320,9/25/2015,9/30/2015,Standard Class,EB-13870,Emily Burns,Consumer,United States,Orem,Utah,84057,West,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,1044.6300,3,0.00,240.2649
27,28,US-2015-150630,9/17/2015,9/21/2015,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,Pennsylvania,19140,East,FUR-BO-10004834,Furniture,Bookcases,"Riverside Palais Royal Lawyers Bookcase, Royal...",3083.4300,7,0.50,-1665.0522

In [ ]:
test = table_books.groupby(['Sub-Category','Discount'])['Profit'].sum().reset_index()
test = test.sort_values(by=['Sub-Category', 'Discount'])
test

   Sub-Category  Discount      Profit
0     Bookcases      0.00   6075.7117
1     Bookcases      0.15   1418.9915
2     Bookcases      0.20    130.5022
3     Bookcases      0.30   -555.8726
4     Bookcases      0.32  -2391.1377
5     Bookcases      0.50  -4255.8117
6     Bookcases      0.70  -3894.9394
7        Tables      0.00  13276.2997
8        Tables      0.20   -303.5580
9        Tables      0.30  -3402.3276
10       Tables      0.40 -16187.3968
11       Tables      0.45  -2493.1111
12       Tables      0.50  -8615.3873

In [ ]:
px.line(test, x='Discount', y='Profit', color='Sub-Category', markers=True)

In [ ]:
table_books.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
10,11,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032,West,FUR-TA-10001539,Furniture,Tables,Chromcraft Rectangular Conference Tables,1706.1840,9,0.20,85.3092
24,25,CA-2015-106320,9/25/2015,9/30/2015,Standard Class,EB-13870,Emily Burns,Consumer,United States,Orem,Utah,84057,West,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,1044.6300,3,0.00,240.2649
27,28,US-2015-150630,9/17/2015,9/21/2015,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,Pennsylvania,19140,East,FUR-BO-10004834,Furniture,Bookcases,"Riverside Palais Royal Lawyers Bookcase, Royal...",3083.4300,7,0.50,-1665.0522

In [ ]:
quantity_discount_tables_and_books = table_books.groupby(['Sub-Category','Quantity'])['Sales'].sum().reset_index()
quantity_discount_tables_and_books

   Sub-Category  Quantity       Sales
0     Bookcases         1   3195.0760
1     Bookcases         2  15117.7658
2     Bookcases         3  16872.4812
3     Bookcases         4  11179.3464
4     Bookcases         5  23824.0140
5     Bookcases         6  11038.9104
6     Bookcases         7  13423.1244
7     Bookcases         8   5697.7920
8     Bookcases         9   6525.2151
9     Bookcases        10   5988.0340
10    Bookcases        12    681.4080
11    Bookcases        13   1336.8290
12       Tables         1   6587.3915
13       Tables         2  20356.1960
14       Tables         3  41417.2155
15       Tables         4  22172.8840
16       Tables         5  22031.2775
17       Tables         6  18149.2590
18       Tables         7  28790.6745
19       Tables         8  12892.0400
20       Tables         9  17584.3080
21       Tables        10   3718.9200
22       Tables        12   7349.3520
23       Tables        13   5916.0140

In [ ]:
px.line(
    quantity_discount_tables_and_books,
    x = 'Quantity',
    y = 'Sales',
    color = 'Sub-Category'
)

Moderate level relation have been represented here quantity have reduced along with the sales
people tends to purchase high price purchase with limited quantity

In [ ]:
from numpy import dtypes
only_numeric = table_books.select_dtypes(include = ['int','float'])

In [ ]:
correlation = only_numeric.corr()

In [ ]:
px.imshow(
    correlation,
    text_auto=True
)

Investigating what if the loss or negative profit is due to the high quantity perchase

In [ ]:
profit_table_books_quantity = table_books.groupby(['Sub-Category','Quantity'])['Profit'].sum().reset_index()
profit_table_books_quantity

   Sub-Category  Quantity     Profit
0     Bookcases         1   -73.4031
1     Bookcases         2   280.9272
2     Bookcases         3  -404.3121
3     Bookcases         4  -725.8488
4     Bookcases         5   366.3105
5     Bookcases         6  -472.2672
6     Bookcases         7 -2888.1748
7     Bookcases         8   109.6320
8     Bookcases         9   378.1215
9     Bookcases        10  -117.5840
10    Bookcases        12    42.5880
11    Bookcases        13    31.4548
12       Tables         1 -1022.3987
13       Tables         2 -1618.5738
14       Tables         3 -3780.1116
15       Tables         4 -1779.5604
16       Tables         5 -2192.9060
17       Tables         6 -2564.2224
18       Tables         7 -3039.8123
19       Tables         8  -231.7392
20       Tables         9   407.0097
21       Tables        10    66.3790
22       Tables        12  -463.2744
23       Tables        13 -1506.2710

In [ ]:
px.line(
    profit_table_books_quantity,
    x = 'Quantity',
    y = 'Profit',
    color = 'Sub-Category'
)

Books and table losses are losses are high at the low quantity range

Obervating only Negative P.O.V to see the pattern in it

In [ ]:
negative_losses = table_books[df['Profit'] < 0].groupby(['Sub-Category','Quantity'])['Profit'].sum().reset_index()
negative_losses

/tmp/ipykernel_3731/3615119192.py:1: UserWarning:

Boolean Series key will be reindexed to match DataFrame index.

   Sub-Category  Quantity     Profit
0     Bookcases         1  -300.1687
1     Bookcases         2 -1035.3232
2     Bookcases         3 -1620.2031
3     Bookcases         4 -1307.6184
4     Bookcases         5 -1662.4720
5     Bookcases         6 -1308.4188
6     Bookcases         7 -3778.7582
7     Bookcases         8  -395.7472
8     Bookcases         9  -555.4224
9     Bookcases        10  -188.0740
10       Tables         1 -1302.7050
11       Tables         2 -3156.2314
12       Tables         3 -6413.5215
13       Tables         4 -3155.7064
14       Tables         5 -3883.7605
15       Tables         6 -3410.0970
16       Tables         7 -5396.2405
17       Tables         8 -1639.9456
18       Tables         9 -1251.5760
19       Tables        10  -320.4560
20       Tables        12  -619.5960
21       Tables        13 -1862.3124

In [ ]:
px.line(
    negative_losses,
    x = 'Quantity',
    y = 'Profit',
    color = 'Sub-Category'
)

Losses pattern represent that the mostly at the limited range high quantity supports less losses

In [ ]:
positive_quantity = table_books[table_books['Profit'] > 0].groupby(['Sub-Category','Quantity'])['Profit'].sum().reset_index()
positive_quantity

   Sub-Category  Quantity     Profit
0     Bookcases         1   226.7656
1     Bookcases         2  1316.2504
2     Bookcases         3  1215.8910
3     Bookcases         4   581.7696
4     Bookcases         5  2028.7825
5     Bookcases         6   836.1516
6     Bookcases         7   890.5834
7     Bookcases         8   505.3792
8     Bookcases         9   933.5439
9     Bookcases        10    70.4900
10    Bookcases        12    42.5880
11    Bookcases        13    31.4548
12       Tables         1   280.3063
13       Tables         2  1537.6576
14       Tables         3  2633.4099
15       Tables         4  1376.1460
16       Tables         5  1690.8545
17       Tables         6   845.8746
18       Tables         7  2356.4282
19       Tables         8  1408.2064
20       Tables         9  1658.5857
21       Tables        10   386.8350
22       Tables        12   156.3216
23       Tables        13   356.0414

In [ ]:
px.line(
    positive_quantity,
    x = 'Quantity',
    y = 'Profit',
    color = 'Sub-Category'
)

Not much of a relation here

In [ ]:
table_books.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
10,11,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032,West,FUR-TA-10001539,Furniture,Tables,Chromcraft Rectangular Conference Tables,1706.1840,9,0.20,85.3092
24,25,CA-2015-106320,9/25/2015,9/30/2015,Standard Class,EB-13870,Emily Burns,Consumer,United States,Orem,Utah,84057,West,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,1044.6300,3,0.00,240.2649
27,28,US-2015-150630,9/17/2015,9/21/2015,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,Pennsylvania,19140,East,FUR-BO-10004834,Furniture,Bookcases,"Riverside Palais Royal Lawyers Bookcase, Royal...",3083.4300,7,0.50,-1665.0522

In [ ]:
shipmode_sales_effect = table_books.groupby(['Sub-Category','Ship Mode'])['Sales'].sum().reset_index()
shipmode_sales_effect

  Sub-Category       Ship Mode        Sales
0    Bookcases     First Class   21065.3189
1    Bookcases        Same Day    2970.5820
2    Bookcases    Second Class   22307.2129
3    Bookcases  Standard Class   68536.8825
4       Tables     First Class   28800.7760
5       Tables        Same Day    9644.3470
6       Tables    Second Class   43693.7475
7       Tables  Standard Class  124826.6615

In [ ]:
px.bar(
    shipmode_sales_effect,
    x = 'Ship Mode',
    y = 'Sales',
    color = 'Sub-Category',
    barmode = 'group'
)

In [ ]:
from scipy.stats import f_oneway

first_class = table_books[table_books['Ship Mode'] == 'First Class']['Sales']
same_day = table_books[table_books['Ship Mode'] == 'Same Day']['Sales']
second_day = table_books[table_books['Ship Mode'] == 'Second Class']['Sales']
standard_class = table_books[table_books['Ship Mode'] == 'Standard Class']['Sales']

result = f_oneway(first_class, same_day, second_day, standard_class)

print(result.pvalue)

0.36598726357194494

In [ ]:
from scipy.stats import f_oneway

first_class = table_books[table_books['Ship Mode'] == 'First Class']['Profit']
same_day = table_books[table_books['Ship Mode'] == 'Same Day']['Profit']
second_day = table_books[table_books['Ship Mode'] == 'Second Class']['Profit']
standard_class = table_books[table_books['Ship Mode'] == 'Standard Class']['Profit']

result = f_oneway(first_class, same_day, second_day, standard_class)

print(result.pvalue)

0.6990392359223004

In [ ]:
discount_shipmode = table_books.groupby(['Sub-Category','Ship Mode'])['Discount'].value_counts().reset_index()
discount_shipmode

   Sub-Category       Ship Mode  Discount  count
0     Bookcases     First Class      0.00     12
1     Bookcases     First Class      0.15     11
2     Bookcases     First Class      0.20      7
3     Bookcases     First Class      0.30      6
4     Bookcases     First Class      0.32      6
5     Bookcases     First Class      0.70      4
6     Bookcases     First Class      0.50      3
7     Bookcases        Same Day      0.15      3
8     Bookcases        Same Day      0.00      2
9     Bookcases        Same Day      0.20      2
10    Bookcases    Second Class      0.00     16
11    Bookcases    Second Class      0.15     10
12    Bookcases    Second Class      0.20      8
13    Bookcases    Second Class      0.50      6
14    Bookcases    Second Class      0.32      5
15    Bookcases    Second Class      0.70      3
16    Bookcases  Standard Class      0.00     30
17    Bookcases  Standard Class      0.20     29
18    Bookcases  Standard Class      0.15     28
19    Bookcases  Standard Class      0.32     16
20    Bookcases  Standard Class      0.50      9
21    Bookcases  Standard Class      0.70      8
22    Bookcases  Standard Class      0.30      4
23       Tables     First Class      0.00     13
24       Tables     First Class      0.30     10
25       Tables     First Class      0.40     10
26       Tables     First Class      0.20      9
27       Tables     First Class      0.50      5
28       Tables        Same Day      0.40      8
29       Tables        Same Day      0.20      7
30       Tables        Same Day      0.00      3
31       Tables        Same Day      0.30      3
32       Tables    Second Class      0.00     15
33       Tables    Second Class      0.20     15
34       Tables    Second Class      0.40     15
35       Tables    Second Class      0.30      9
36       Tables    Second Class      0.50      6
37       Tables    Second Class      0.45      1
38       Tables  Standard Class      0.40     42
39       Tables  Standard Class      0.00     41
40       Tables  Standard Class      0.20     40
41       Tables  Standard Class      0.30     32
42       Tables  Standard Class      0.50     25
43       Tables  Standard Class      0.45     10

In [ ]:
px.bar(
    discount_shipmode,
    x = 'Discount',
    y = 'count',
    color = 'Ship Mode',
    barmode = 'group',
    facet_col='Sub-Category'
)

In [ ]:
def func(test):
  if test > 0:
    return 'yes'
  else:
    return 'no'

In [ ]:
table_books['Discount Applied'] = table_books['Discount'].apply(func)

/tmp/ipykernel_3731/2427178999.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
table_books.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Discount Applied
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,no
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,yes
10,11,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032,West,FUR-TA-10001539,Furniture,Tables,Chromcraft Rectangular Conference Tables,1706.1840,9,0.20,85.3092,yes
24,25,CA-2015-106320,9/25/2015,9/30/2015,Standard Class,EB-13870,Emily Burns,Consumer,United States,Orem,Utah,84057,West,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,1044.6300,3,0.00,240.2649,no
27,28,US-2015-150630,9/17/2015,9/21/2015,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,Pennsylvania,19140,East,FUR-BO-10004834,Furniture,Bookcases,"Riverside Palais Royal Lawyers Bookcase, Royal...",3083.4300,7,0.50,-1665.0522,yes

In [ ]:
fig = pd.crosstab(table_books['Discount Applied'],table_books['Ship Mode'])
fig

Ship Mode         First Class  Same Day  Second Class  Standard Class
Discount Applied
no                         25         5            31              71
yes                        71        23            78             243

In [ ]:
from scipy.stats import chi2_contingency

ee,p,exp,stats = chi2_contingency(fig)
p

np.float64(0.5134740833042875)

In [ ]:
fig = pd.crosstab(table_books['Discount Applied'],table_books['Segment'])
fig

Segment           Consumer  Corporate  Home Office
Discount Applied
no                      64         40           28
yes                    226        130           59

In [ ]:
ee,p,exp,stats  = chi2_contingency(fig)
p

np.float64(0.15041457726452856)

In [ ]:
regionwise_subcategory = table_books.groupby('Region')['Sub-Category'].value_counts().reset_index()
regionwise_subcategory

    Region Sub-Category  count
0  Central       Tables     72
1  Central    Bookcases     50
2     East       Tables     80
3     East    Bookcases     70
4    South       Tables     51
5    South    Bookcases     28
6     West       Tables    116
7     West    Bookcases     80

In [ ]:
px.bar(
    regionwise_subcategory,
    x = 'Region',
    y = 'count',
    color = 'Sub-Category',
    barmode = 'group'
)

In [ ]:
sale_region_sub_category = table_books.groupby(['Sub-Category','Region'])['Sales'].sum().reset_index()
sale_region_sub_category

  Sub-Category   Region       Sales
0    Bookcases  Central  24157.1768
1    Bookcases     East  43819.3340
2    Bookcases    South  10899.3620
3    Bookcases     West  36004.1235
4       Tables  Central  39154.9710
5       Tables     East  39139.8070
6       Tables    South  43916.1920
7       Tables     West  84754.5620

In [ ]:
px.bar(
    sale_region_sub_category,
    x = 'Region',
    y = 'Sales',
    color = 'Sub-Category',
    barmode = 'group'
)

In [ ]:
central = table_books[table_books['Region'] == 'Central']['Sales']
east = table_books[table_books['Region'] == 'East']['Sales']
south = table_books[table_books['Region'] == 'South']['Sales']
west = table_books[table_books['Region'] == 'West']['Sales']

result = f_oneway(central, east, south, west)

print(result.pvalue)

0.20689537990010218

In [ ]:
fig = pd.crosstab(table_books['Region'],table_books['Sub-Category'])

result = chi2_contingency(fig)
print(result.pvalue)

0.40998886376101285

In [ ]:
table_books['Order Date'] = pd.to_datetime(table_books['Order Date'])

/tmp/ipykernel_3731/319055721.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
table_books['year'] = table_books['Order Date'].dt.year

/tmp/ipykernel_3731/3650555297.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
test = table_books.groupby(['Sub-Category','year'])['Profit'].sum().reset_index()
test

  Sub-Category  year     Profit
0    Bookcases  2014  -346.1707
1    Bookcases  2015 -2755.2302
2    Bookcases  2016   212.4710
3    Bookcases  2017  -583.6261
4       Tables  2014 -3124.0427
5       Tables  2015 -3509.8019
6       Tables  2016 -2950.9418
7       Tables  2017 -8140.6947

In [ ]:
px.line(
    test,
    x = 'year',
    y ='Profit',
    color = 'Sub-Category'
)

this plot matches with the previous line chart with discount it

In [ ]:
df['Customer ID'].unique().shape

(793,)

Does Customer Purchases Influence the Losses

In [ ]:
customer_purchase = df.groupby('Customer ID')['Discount'].mean().reset_index()
customer_purchase.head()

  Customer ID  Discount
0    AA-10315  0.090909
1    AA-10375  0.080000
2    AA-10480  0.016667
3    AA-10645  0.063889
4    AB-10015  0.066667

In [ ]:
customer_behavior = df.groupby(['Customer ID', 'Customer Name']).agg(
    Total_Sales=('Sales', 'sum'),
    Net_Profit=('Profit', 'sum'),
    Avg_Discount=('Discount', 'mean')
).reset_index().sort_values("Net_Profit", ascending=False)

customer_behavior.head()

    Customer ID  Customer Name  Total_Sales  Net_Profit  Avg_Discount
741    TC-20980   Tamara Chand    19052.218   8981.3239      0.116667
621    RB-19360   Raymond Buch    15117.339   6976.0959      0.094444
669    SC-20095   Sanjit Chand    14142.334   5757.4119      0.063636
327    HL-15040   Hunter Lopez    12873.298   5622.4292      0.018182
6      AB-10105  Adrian Barton    14473.571   5444.8055      0.240000

In [ ]:
top_five = customer_behavior
top_five.head()

    Customer ID  Customer Name  Total_Sales  Net_Profit  Avg_Discount
741    TC-20980   Tamara Chand    19052.218   8981.3239      0.116667
621    RB-19360   Raymond Buch    15117.339   6976.0959      0.094444
669    SC-20095   Sanjit Chand    14142.334   5757.4119      0.063636
327    HL-15040   Hunter Lopez    12873.298   5622.4292      0.018182
6      AB-10105  Adrian Barton    14473.571   5444.8055      0.240000

In [ ]:
top_losses = customer_behavior[customer_behavior['Net_Profit'] <= 0].sort_values("Net_Profit", ascending = True)
top_losses.head()

    Customer ID   Customer Name  Total_Sales  Net_Profit  Avg_Discount
180    CS-12505   Cindy Stewart     5690.055  -6626.3895      0.200000
310    GT-14635  Grant Thornton     9351.212  -4108.6589      0.250000
459    LF-17185     Luke Foster     3930.509  -3583.9770      0.318750
711    SR-20425  Sharelle Roach     3233.481  -3333.9144      0.366667
322    HG-14965   Henry Goldwyn     3247.642  -2797.9635      0.170588

In [ ]:
customer_category = df.groupby(['Customer ID','Category','Sub-Category']).agg(
    Total_Sales=('Sales', 'sum'),
    Net_Profit=('Profit', 'sum'),
    Avg_Discount=('Discount', 'mean')
).reset_index().sort_values("Net_Profit", ascending=False)

customer_category.head()

,Customer ID,Category,Sub-Category,Total_Sales,Net_Profit,Avg_Discount
5618,TC-20980,Technology,Copiers,17499.950,8399.9760,0.00
4689,RB-19360,Technology,Copiers,13999.960,6719.9808,0.00
5041,SC-20095,Office Supplies,Binders,11468.166,5549.1365,0.08
48,AB-10105,Office Supplies,Binders,11068.910,5388.6829,0.30
2457,HL-15040,Technology,Copiers,10499.970,5039.9856,0.00

In [ ]:
unprofitable_customer = df[df['Profit'] <= 0].groupby(['Customer ID','Category'])['Profit'].sum().reset_index()
unprofitable_customer.head()

  Customer ID         Category    Profit
0    AA-10315  Office Supplies -786.0144
1    AA-10645        Furniture   -4.8588
2    AA-10645       Technology  -15.1767
3    AB-10015  Office Supplies   -2.5248
4    AB-10060        Furniture  -73.0548

In [ ]:
px.bar(
    unprofitable_customer,
    x = 'Category',
    y = 'Profit'
)

In [ ]:
region_losses = df[df['Profit'] <= 0].groupby(['Customer ID','Region','State'])['Profit'].sum().reset_index()
region_losses.head()

  Customer ID   Region         State    Profit
0    AA-10315  Central         Texas -786.0144
1    AA-10645     East  Pennsylvania  -20.0355
2    AB-10015  Central         Texas   -2.5248
3    AB-10060     West    Washington  -73.0548
4    AB-10105  Central         Texas -181.5686

In [ ]:
px.bar(
    region_losses,
    x = 'Region',
    y = 'Profit'
)

In [ ]:
region_losses = df[df['Profit'] <= 0].groupby(['Customer ID','State'])['Profit'].sum().reset_index()
region_losses.sort_values('Profit',ascending = True).head()

     Customer ID           State     Profit
259     CS-12505            Ohio -6904.3700
488     GT-14635  North Carolina -3839.9904
718     LF-17185           Texas -3805.5490
1116    SR-20425        Colorado -3431.6122
506     HG-14965        Illinois -2929.4845